# analysis/analysis_prompts.py

# Ensure all text output in the JSON from Gemini is in ENGLISH.

LONGITUDINAL_BRAND_EVOLUTION_PROMPT_TEMPLATE = """
You are an expert technology analyst synthesising information from multiple product reviews over several generations for a specific brand.
The video review analyses provided were generated by an AI and include structured data like 'overall_assessment', 'feature_analysis', 'pricing_and_value', 'comparison_context', and 'non_verbal_cues'.

Brand: {brand_name}
Product Line: {product_line}
Generations Covered (with release years and number of source review documents used):
{product_list_details_with_years} 
# Example: 
# - iPhone 11 Pro Max (2019) - (18 reviews)
# - iPhone 12 Pro Max (2020) - (21 reviews)
# - ...

The following is a batch of individual video review analyses for these products. Each analysis corresponds to one video review.
--- BATCH OF REVIEW ANALYSES START ---
{concatenated_json_analyses}
--- BATCH OF REVIEW ANALYSES END ---

Based ONLY on the provided batch of review analyses data:

Part 1: Textual Summary (Comprehensive, in ENGLISH, 400-600 words):
Write a narrative that addresses:
1.  The overall sentiment trend towards {brand_name}'s {product_line} across these generations. How did reviewers generally feel, and did this change?
2.  Evolution of Key Positive Features: Identify 3-5 consistently praised or significantly improved features (e.g., Camera, Performance, Battery, Design, Ecosystem). Describe how their perception evolved.
3.  Evolution of Key Negative Features/Criticisms: Identify 3-5 recurring criticisms or areas that saw negative shifts. How were these addressed (or not) over generations?
4.  Shifts in Reviewer Focus: Did reviewers start paying more attention to different aspects of the {product_line} over time?
5.  Impact of Competition (if evident in reviews): Were there any mentions of competitive pressures influencing {brand_name}'s product evolution or reviewer perception?
Use specific examples, direct or paraphrased quotes (clearly indicating they are from the provided review data), and insights from the 'non_verbal_cues' if they offer strong corroborating or contrasting points.

Part 2: Structured JSON Output (All text in ENGLISH):
Provide a JSON object with the following structure. Ensure all string values are in English.
{{
    "analysis_type": "Longitudinal Brand Evolution",
    "brand": "{brand_name}",
    "product_line": "{product_line}",
    "generations_analyzed": [{generation_entry_list_for_json}], // e.g., ["iPhone 11 Pro Max (2019)", "iPhone 12 Pro Max (2020)"]
    "overall_sentiment_trend_summary": "STRING (Concise summary of point 1 from your textual analysis)",
    "feature_evolution_analysis": [
        {{
            "feature_name": "STRING (e.g., Camera System, Battery Life, Performance, Design, Display, Software/Ecosystem, Price/Value)",
            "evolution_narrative": "STRING (Detailed description of how this feature and its perception evolved across the analyzed generations, citing specific product generations if possible)",
            "sentiment_trend_across_generations": "ENUM('Strongly Improving', 'Moderately Improving', 'Consistent Positive', 'Mixed/Fluctuating', 'Consistent Negative', 'Moderately Declining', 'Strongly Declining', 'Became Key Factor', 'Less Emphasized Over Time')",
            "key_generational_milestones": ["STRING (e.g., 'iPhone 13 Pro Max: Introduction of ProMotion display', 'iPhone 11 Pro Max: Major leap in battery life')"]
        }}
        // Aim for 5-7 key features
    ],
    "recurring_positive_themes": ["STRING (Common positive points consistently mentioned across multiple generations)"],
    "recurring_negative_themes": ["STRING (Common negative points consistently mentioned across multiple generations)"],
    "significant_opinion_shifts_observed": [
        {{
            "generation_product_name": "STRING (e.g., iPhone 12 Pro Max)",
            "shift_description": "STRING (Describe a notable shift in sentiment or focus for this generation compared to previous or expectations, e.g., 'Marked improvement in low-light photography changed perception', 'Price increase became a major talking point')",
            "supporting_evidence_summary": "STRING (Briefly, what in the review data supports this observed shift?)"
        }}
    ],
    "overall_evolution_conclusion": "STRING (Your final overarching summary of {brand_name}'s {product_line} evolution based on the collective reviewer sentiment)"
}}
"""

COMPARATIVE_PRODUCT_ANALYSIS_PROMPT_TEMPLATE = """
You are an expert technology analyst conducting a comparative review synthesis for a set of competing products from a similar timeframe or market segment.
The video review analyses provided were generated by an AI and include structured data like 'overall_assessment', 'feature_analysis', 'pricing_and_value', 'comparison_context', and 'non_verbal_cues'.

Products Being Compared (with number of source review documents used):
{product_list_details_with_brands_years}
# Example:
# - Apple iPhone 15 Pro Max (2023) - (25 reviews)
# - Samsung Galaxy S24 Ultra (2024) - (23 reviews)
# - Google Pixel 8 Pro (2023) - (19 reviews)

The following is a batch of individual video review analyses for these products. Ensure you consider reviews for all listed products.
--- BATCH OF REVIEW ANALYSES START ---
{concatenated_json_analyses}
--- BATCH OF REVIEW ANALYSES END ---

Based ONLY on the provided batch of review analyses data:

Part 1: Textual Summary (Comprehensive, in ENGLISH, 400-600 words):
Write a narrative that addresses:
1.  Overall Sentiment and Preference: Which product(s) did reviewers generally favour, if any? Was there a clear winner, or was it dependent on priorities? Explain the nuances.
2.  Head-to-Head Feature Comparison: For key features (e.g., Camera System, Performance, Battery Life, Display, Software/Ecosystem, Design, Price/Value), detail the strengths and weaknesses of each product relative to the others.
3.  Unique Selling Propositions (USPs): What were the standout, differentiating features or aspects for each product according to reviewers?
4.  Significant Drawbacks: What were the most commonly cited or impactful weaknesses for each product in this comparison?
5.  Non-Verbal Cues: Did reviewers' non-verbal cues (tone, expressions) consistently reinforce their textual assessment, or were there interesting deviations when discussing specific products or features?
Use specific examples, direct or paraphrased quotes (clearly indicating they are from the provided review data), to support your points.

Part 2: Structured JSON Output (All text in ENGLISH):
Provide a JSON object with the following structure. Ensure all string values are in English.
{{
    "analysis_type": "Comparative Product Analysis",
    "products_compared": [{product_entry_list_for_json}], // e.g., ["Apple iPhone 15 Pro Max", "Samsung Galaxy S24 Ultra", "Google Pixel 8 Pro"]
    "comparison_timeframe_or_segment": "STRING (e.g., 'Flagships of Late 2023/Early 2024', 'Premium Smartphone Segment')",
    "overall_comparative_summary_narrative": "STRING (Concise summary of point 1 from your textual analysis)",
    "feature_by_feature_comparison": [
        {{
            "feature_name": "STRING (e.g., Camera System, Performance, Battery Life, Display, Software/Ecosystem, Design, Price/Value)",
            "product_performance_details": [
                {{
                    "product_name": "STRING",
                    "strengths_in_feature": ["STRING (Specific strength 1 for this product in this feature)"],
                    "weaknesses_in_feature": ["STRING (Specific weakness 1 for this product in this feature)"],
                    "overall_feature_rating_by_reviewers": "ENUM('Excellent/Leader', 'Very Good/Strong Contender', 'Good/Competitive', 'Average/Adequate', 'Below Average/Weakness', 'Mixed')"
                }}
                // One entry per product being compared
            ],
            "cross_product_feature_verdict": "STRING (Overall verdict for this feature across products, e.g., 'iPhone excelled in video, S24U in zoom capabilities, Pixel in computational photography consistency')"
        }}
        // Aim for 5-7 key features
    ],
    "product_specific_highlights": [
        {{
            "product_name": "STRING",
            "key_usps_from_reviews": ["STRING (Unique Selling Proposition 1)"],
            "notable_drawbacks_from_reviews": ["STRING (Significant Drawback 1)"]
        }}
        // One entry per product being compared
    ],
    "reviewer_preference_leaning_overall": "STRING (e.g., 'Slight tilt towards Product X for overall package, but strong cases for Y and Z depending on user needs', 'No single winner, reviewers highlighted different strengths for different users')"
}}
"""
# ––––––––––––––––––––––––––––––––––––––––––––
# ––––––––––––––––––––––––––––––––––––––––––––
# SAAS PRODUCT ANALYSIS PROMPTS

# --- 1. Comparative SaaS Product Analysis Prompt ---
COMPARATIVE_SAAS_ANALYSIS_PROMPT_TEMPLATE = """
You are an expert B2B SaaS technology analyst conducting a comparative review synthesis for a set of competing SaaS products.
The video review analyses provided were generated by an AI and include structured data like 'overall_assessment', 'feature_module_analysis', 'usability_and_ux', 'pricing_and_value_perception', 'customer_support_and_resources', etc., for SaaS products.

Products Being Compared (with number of source review documents used):
{product_list_details_with_brands_years}
# Example:
# - HubSpot CRM Suite (SMB CRM) - (10 reviews)
# - Pipedrive (Sales Pipeline Focus) - (8 reviews)
# - Freshsales (Customer Engagement) - (9 reviews)

The following is a batch of individual video review analyses for these SaaS products. Ensure you consider reviews for all listed products.
--- BATCH OF REVIEW ANALYSES START ---
{concatenated_json_analyses}
--- BATCH OF REVIEW ANALYSES END ---

Based ONLY on the provided batch of review analyses data:

Part 1: Textual Summary (Comprehensive, in ENGLISH, 500-700 words):
Write a narrative that addresses:
1.  Overall Sentiment and Recommendation Strength: Which product(s) did reviewers generally favour for specific business types or needs? Was there a clear winner, or was it dependent on priorities (e.g., ease of use, feature depth, price)?
2.  Ease of Use & User Experience (UX): Compare the onboarding process, day-to-day intuitiveness, and overall UI/UX design appeal as perceived by reviewers.
3.  Core Feature Set Comparison: For 3-5 key SaaS CRM functionalities (e.g., Contact Management, Deal/Pipeline Management, Email Marketing/Automation, Reporting & Analytics, Customization), detail the strengths and weaknesses of each product relative to the others.
4.  Pricing & Value Perception: How did reviewers perceive the pricing models, overall cost, and value for money for each product? Were there mentions of hidden costs or particularly good value tiers?
5.  Customer Support & Resources: What was the general sentiment regarding customer support, documentation, and community resources for each product?
6.  Unique Selling Propositions (USPs) & Key Differentiators: What stood out for each product?
7.  Notable Drawbacks: What were the most commonly cited weaknesses for each product in this comparison?

Use specific examples or paraphrased insights from the review data to support your points.

Part 2: Structured JSON Output (All text in ENGLISH):
Provide a JSON object with the following structure. Ensure all string values are in English.
{{
    "analysis_type": "Comparative SaaS Product Analysis",
    "products_compared": [{product_entry_list_for_json}], // e.g., ["HubSpot CRM Suite", "Pipedrive"]
    "comparison_segment": "{comparison_segment_description}", // e.g., "SMB CRM Showdown for Sales-Focused Teams"
    "overall_comparative_summary_narrative": "STRING (Concise summary of point 1 from your textual analysis)",
    "ease_of_use_ux_comparison": [
        {{
            "product_name": "STRING",
            "perceived_ease_of_use": "ENUM('Very Intuitive', 'Intuitive', 'Average Learning Curve', 'Complex', 'Frustrating', 'Not Clearly Stated')",
            "ui_ux_highlights": "STRING (Key comments on UI/UX from reviewers)",
            "onboarding_experience_notes": "STRING (Comments on onboarding)"
        }}
        // One entry per product
    ],
    "core_feature_comparison": [
        {{
            "feature_category_name": "STRING (e.g., Deal Management, Reporting & Analytics)",
            "product_performance_details": [
                {{
                    "product_name": "STRING",
                    "strengths_in_feature": ["STRING"],
                    "weaknesses_in_feature": ["STRING"],
                    "reviewer_sentiment_on_feature": "ENUM('Strongly Positive', 'Positive', 'Neutral', 'Mixed', 'Negative', 'Strongly Negative')"
                }}
                // One entry per product
            ],
            "cross_product_feature_verdict": "STRING (Overall verdict for this feature category across products)"
        }}
        // 3-5 key feature categories
    ],
    "pricing_value_comparison": [
        {{
            "product_name": "STRING",
            "pricing_model_clarity": "ENUM('Clear', 'Somewhat Clear', 'Confusing', 'Not Mentioned')",
            "perceived_value_for_money": "ENUM('Excellent Value', 'Good Value', 'Fair Price', 'Expensive but Justified', 'Overpriced', 'Not Discussed')",
            "pricing_related_comments": "STRING (Summary of reviewer comments on pricing)"
        }}
        // One entry per product
    ],
    "support_resources_comparison": [
         {{
            "product_name": "STRING",
            "support_sentiment": "ENUM('Excellent', 'Good', 'Adequate', 'Poor', 'Not Mentioned')",
            "resource_quality_comments": "STRING (Comments on docs, community etc.)"
        }}
        // One entry per product
    ],
    "product_specific_synthesis": [
        {{
            "product_name": "STRING",
            "key_usps_from_reviews": ["STRING"],
            "notable_drawbacks_from_reviews": ["STRING"],
            "ideal_customer_profile_suggested": "STRING (e.g., 'Small sales teams needing simplicity', 'Businesses needing deep marketing automation')"
        }}
        // One entry per product
    ],
    "final_recommendation_summary": "STRING (Overall recommendation, considering different needs and priorities)"
}}
"""

# --- 2. Single SaaS Product Deep Dive Prompt ---
SINGLE_SAAS_PRODUCT_DEEP_DIVE_PROMPT_TEMPLATE = """
You are an expert B2B SaaS technology analyst. You are tasked with creating a consolidated deep-dive report for a single SaaS product based on multiple video review analyses.
The video review analyses provided were generated by an AI and include structured data like 'overall_assessment', 'feature_module_analysis', 'usability_and_ux', 'pricing_and_value_perception', etc.

SaaS Product Under Review: {saas_product_name}
Number of Source Review Documents Used: {num_reviews_used}

The following is a batch of individual video review analyses for this specific SaaS product.
--- BATCH OF REVIEW ANALYSES START ---
{concatenated_json_analyses}
--- BATCH OF REVIEW ANALYSES END ---

Based ONLY on the provided batch of review analyses:

Part 1: Textual Summary (Comprehensive, in ENGLISH, 400-600 words):
Write a narrative that synthesizes the collective reviewer sentiment and findings for "{saas_product_name}". Address:
1.  Overall Consensus: What is the general prevailing sentiment towards the product? Is it largely positive, negative, or mixed?
2.  Key Strengths: What are the 3-5 most consistently praised features, modules, or aspects of the product?
3.  Key Weaknesses/Pain Points: What are the 3-5 most common criticisms, areas of frustration, or significant drawbacks mentioned by reviewers?
4.  User Experience (UX) & Ease of Use: Summarize the collective opinion on the product's usability, learning curve, and UI/UX.
5.  Pricing & Value Proposition: How do reviewers generally perceive its pricing structure and overall value for money?
6.  Ideal User/Business Profile: Based on the reviews, who is this product best suited for (e.g., business size, industry, specific needs)?
7.  Customer Support & Resources: What is the general view on the quality of support and available resources (docs, community)?

Use specific examples or paraphrased insights from the review data.

Part 2: Structured JSON Output (All text in ENGLISH):
Provide a JSON object with the following structure. Ensure all string values are in English.
{{
    "analysis_type": "Single SaaS Product Deep Dive",
    "product_name": "{saas_product_name}",
    "num_source_reviews": {num_reviews_used_for_json}, // Integer
    "overall_sentiment_summary": {{
        "consensus_sentiment": "ENUM('Overwhelmingly Positive', 'Mostly Positive', 'Mixed with Positive Lean', 'Mixed with Negative Lean', 'Mostly Negative', 'Overwhelmingly Negative')",
        "brief_narrative": "STRING (2-3 sentence summary of overall perception)"
    }},
    "synthesized_strengths": [ // Top 3-5
        {{
            "strength_area": "STRING (e.g., 'Ease of Use for Beginners', 'Powerful Automation Capabilities', 'Excellent Reporting')",
            "description_of_strength": "STRING (Details of why this is a strength, based on reviews)",
            "supporting_reviewer_themes": ["STRING (Common phrases or ideas from reviews supporting this)"]
        }}
    ],
    "synthesized_weaknesses": [ // Top 3-5
        {{
            "weakness_area": "STRING (e.g., 'Steep Learning Curve for Advanced Features', 'Pricing for Small Teams', 'Limited Customization in X Module')",
            "description_of_weakness": "STRING (Details of why this is a weakness, based on reviews)",
            "recurring_criticisms": ["STRING (Common complaints or issues from reviews)"]
        }}
    ],
    "user_experience_summary": {{
        "overall_ux_rating_consensus": "ENUM('Excellent', 'Good', 'Average', 'Fair', 'Poor')",
        "learning_curve_perception": "STRING (e.g., 'Quick to learn basic features', 'Requires significant time for mastery')",
        "ui_feedback_highlights": "STRING (Summary of comments on UI design and navigation)"
    }},
    "pricing_and_value_summary": {{
        "common_pricing_tier_perception": "STRING (e.g., 'Entry-tier seen as good value, higher tiers perceived as expensive')",
        "value_for_money_consensus": "ENUM('Excellent', 'Good', 'Fair', 'Poor', 'Depends on Use Case')",
        "pricing_related_concerns": ["STRING (e.g., 'Lack of transparent pricing for add-ons', 'Per-user cost adds up quickly')"]
    }},
    "customer_support_summary": {{
        "general_support_sentiment": "ENUM('Highly Praised', 'Generally Good', 'Inconsistent', 'Needs Improvement', 'Poorly Rated', 'Not Frequently Mentioned')",
        "comments_on_resources": "STRING (Summary of feedback on documentation, community, tutorials)"
    }},
    "ideal_customer_profile_synthesized": {{
        "business_sizes": ["STRING (e.g., 'Startups', 'Small Businesses (1-50)', 'Mid-Market (51-500)')"],
        "key_needs_addressed_well": ["STRING (e.g., 'Basic contact management', 'Sales automation for growing teams', 'Integrated marketing and sales')"],
        "not_ideal_for": ["STRING (e.g., 'Large enterprises needing deep customization', 'Solopreneurs with very simple needs')"]
    }},
    "overall_recommendation_trend": "STRING (e.g., 'Highly recommended for SMBs focused on growth', 'Recommended with caveats regarding pricing complexity')"
}}
"""

# --- 4. SaaS Category Key Buying Factors Prompt ---
SAAS_CATEGORY_KEY_BUYING_FACTORS_PROMPT_TEMPLATE = """
You are an expert B2B SaaS market analyst. Your task is to identify key buying factors, decision drivers, and prominent sentiment themes across a category of SaaS products, based on a collection of individual video review analyses.

SaaS Category Under Analysis: {saas_category_name} (e.g., "CRM Software for SMBs")
Total Number of Review Analyses Considered: {total_reviews_considered} documents from various products within this category.
Products Included in this Category Analysis (example, actual list not explicitly passed in detail here but influences the data):
{example_product_list_for_context}
# Example: Data includes reviews for HubSpot, Pipedrive, Zoho CRM, Freshsales, etc.

The following is a batch of individual video review analyses for VARIOUS products within the "{saas_category_name}" category.
--- BATCH OF REVIEW ANALYSES START ---
{concatenated_json_analyses}
--- BATCH OF REVIEW ANALYSES END ---

Based ONLY on the provided batch of review analyses data from across the category:

Part 1: Textual Summary (Comprehensive, in ENGLISH, 400-600 words):
Write a narrative that addresses:
1.  Dominant Positive Themes: What are the 3-5 most common aspects or features that reviewers consistently praise across different products in the "{saas_category_name}" category? These are general positive drivers.
2.  Dominant Negative Themes/Concerns: What are the 3-5 most common pain points, criticisms, or concerns that reviewers frequently raise about products in this category? These are general negative drivers or areas for improvement.
3.  Key Decision Factors: When reviewers compare products or make recommendations, what are the 2-3 most critical factors they seem to weigh heavily (e.g., ease of use, specific feature set, price, integration capability, customer support)?
4.  Emerging Trends or Expectations: Are there any features, functionalities, or user expectations that seem to be gaining importance or are frequently requested by reviewers for this SaaS category?
5.  Price Sensitivity & Value Perception: What's the general sentiment around pricing in this category? Are users price-sensitive? How is "value" typically defined or perceived by reviewers?

Use specific examples or paraphrased insights from the review data, illustrating how these themes manifest across different (unnamed or generalized) products.

Part 2: Structured JSON Output (All text in ENGLISH):
Provide a JSON object with the following structure. Ensure all string values are in English.
{{
    "analysis_type": "SaaS Category Key Buying Factors",
    "saas_category_analyzed": "{saas_category_name}",
    "total_source_reviews_for_category": {total_reviews_considered_for_json}, // Integer
    "key_positive_sentiment_drivers_across_category": [
        {{
            "driver_name": "STRING (e.g., 'Intuitive User Interface', 'Robust Automation Features', 'Responsive Customer Support')",
            "description": "STRING (Explanation of why this is a positive driver, with examples of how it's expressed)",
            "frequency_observed": "ENUM('Very High', 'High', 'Moderate')" // Subjective assessment
        }}
        // 3-5 drivers
    ],
    "key_negative_sentiment_drivers_or_concerns_across_category": [
        {{
            "driver_name": "STRING (e.g., 'Complex Onboarding Processes', 'Opaque or High Pricing', 'Limited Integration Options with X')",
            "description": "STRING (Explanation of why this is a negative driver/concern)",
            "frequency_observed": "ENUM('Very High', 'High', 'Moderate')"
        }}
        // 3-5 drivers
    ],
    "critical_decision_factors_identified": [
        {{
            "factor_name": "STRING (e.g., 'Ease of Implementation', 'Scalability for Growth', 'Specific Niche Feature Availability')",
            "importance_level": "ENUM('Critical', 'Very Important', 'Important')",
            "explanation": "STRING (Why this factor is crucial for decision-making in this category)"
        }}
        // 2-3 factors
    ],
    "emerging_trends_or_reviewer_expectations": [
        {{
            "trend_or_expectation": "STRING (e.g., 'AI-Powered Insights', 'Deeper Native Integrations with Finance Tools', 'More Flexible Mobile Access')",
            "details": "STRING (How reviewers are discussing this)"
        }}
    ],
    "category_price_sensitivity_and_value_summary": {{
        "general_price_sensitivity": "ENUM('High', 'Moderate', 'Low', 'Varies by Segment')",
        "common_value_metrics": ["STRING (e.g., 'Time saved through automation', 'Improved sales conversion', 'Better customer retention')"],
        "pricing_model_preferences_or_complaints": "STRING (e.g., 'Preference for transparent tiered pricing', 'Complaints about per-user fees scaling poorly')"
    }},
    "overall_category_maturity_perception": "STRING (e.g., 'Mature category with established players', 'Evolving category with rapid innovation', 'Fragmented with many niche solutions')"
}}
"""